name = "winpods-releases-api"
main = "src/index.ts"
compatibility_date = "2025-03-13"

[observability]
enabled = true
head_sampling_rate = 0.1

[vars]
CACHE_KEY = "winpods:latest-release"
CACHE_TTL = 300

[[kv_namespaces]]
binding = "KV"
id = "301de9ceebd040a6b817a9e2b749771f"
