[package]
name = "device"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { path = "../utils" }
windows.workspace = true
windows-collections.workspace = true
serde.workspace = true
serde_json.workspace = true
