name: "Setup Tauri"
description: "Install Tauri dependencies"
runs:
  using: "composite"
  steps:
    - name: Tauri dependencies
      shell: bash
      run: |
        sudo apt update && sudo apt install -y \
          libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libxdo-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          webkit2gtk-driver \
          xvfb
