name: Rust CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  clippy:
    name: Clippy Linting
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: ./.github/actions/setup-rust

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            C:\Users\runneradmin\.cargo\registry
            C:\Users\runneradmin\.cargo\git
            target
          key: cargo-windows-${{ hashFiles('Cargo.lock') }}-clippy
          restore-keys: |
            cargo-windows-

      - name: Run Clippy
        uses: ./.github/actions/ci/clippy

  test:
    name: Run Tests
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: ./.github/actions/setup-rust

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            C:\Users\runneradmin\.cargo\registry
            C:\Users\runneradmin\.cargo\git
            target
          key: cargo-windows-${{ hashFiles('Cargo.lock') }}-test
          restore-keys: |
            cargo-windows-

      - name: Run Tests
        uses: ./.github/actions/ci/test
